
name: Deploy the webpage content to Pages

on:
  # Runs on pushes to the main branch - Means it will also run when PR is merged
  push:
    branches: ["main"]
  # Allows manual triggering from the Actions tab
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout the github repository
        uses: actions/checkout@v4
      - name: setup the github pages
        uses: actions/configure-pages@v5
      - name: upload  the artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: deploy to the gitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
